import {execFile} from "node:child_process";
import {existsSync} from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {promisify} from "node:util";
// A raw `pg` client is used here purely to hold a Postgres advisory lock and
// probe reachability before the schema exists — `lib/db.ts`'s Prisma Proxy
// must not be touched this early (see server/src/lib/db.ts), and this is not
// a repository-owned domain query, so a direct `pg` connection confined to
// `lib/` is consistent with CLAUDE.md's Prisma-access rule.
import {Client} from "pg";
import {resolvePrismaCliEntrypoint} from "./prisma-cli.js";

const execFileAsync = promisify(execFile);
const __dirname = path.dirname(fileURLToPath(import.meta.url));

export type SchemaSyncOutcome =
    | "skipped"
    | "unreachable"
    | "lock-not-acquired"
    | "already-current"
    | "applied"
    | "failed";

export interface SchemaSyncResult {
    outcome: SchemaSyncOutcome;
    detail?: string;
}

export interface CliRunResult {
    code: number;
    stdout: string;
    stderr: string;
}

export type RunCliFn = (argv: string[]) => Promise<CliRunResult>;

/**
 * Narrow query port exposed by an acquired lock — deliberately not the raw
 * `pg.Client` type, so callers (and unit tests) never need to know about
 * `pg` at all, only this one-method shape.
 */
export type QueryFn = (sql: string) => Promise<{rows: Array<Record<string, unknown>>}>;

export type LockAcquisitionResult =
    | {status: "unreachable"; host: string; port: string}
    | {status: "not-acquired"}
    | {status: "acquired"; release: () => Promise<void>; query: QueryFn};

export type AcquireLockFn = () => Promise<LockAcquisitionResult>;

export interface SchemaSyncDeps {
    runCli?: RunCliFn;
    acquireLock?: AcquireLockFn;
}

// The literal migration folder name generated by `prisma migrate diff
// --from-empty --to-schema server/prisma/schema --script` (see
// server/prisma/migrations/0_init/migration.sql) and the exact name the
// baseline resolve step below must record as applied. These two things are
// one value on purpose — if either changes independently, the baseline
// silently stops matching the folder that actually exists on disk.
export const BASELINE_MIGRATION_NAME = "0_init";

// Fixed, application-chosen Postgres advisory-lock key (session-level,
// non-blocking try-variant). Any int works as long as it's stable and not
// reused elsewhere in the codebase — this is the only advisory lock Docktor
// takes.
const ADVISORY_LOCK_KEY = 875_142_001;

// A handful of attempts over roughly thirty seconds — the compose file
// already gates container start on `db: condition: service_healthy`, so this
// only needs to cover the residual race, not act as the primary readiness
// check.
const REACHABILITY_RETRY_ATTEMPTS = 6;
const REACHABILITY_RETRY_DELAY_MS = 5_000;
const REACHABILITY_CONNECT_TIMEOUT_MS = 5_000;

// `prisma migrate deploy`'s no-op wording — case-insensitive, tolerating
// both the singular and plural forms observed across Prisma CLI versions.
// Task 3 of 09-03-PLAN.md pins this against a real invocation's captured
// output; treat any correction there as authoritative over this comment.
const NO_PENDING_MIGRATIONS_REGEX = /no pending migrations?/i;

function sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Parses only the host and port out of DATABASE_URL for logging. Never logs
 * the full connection string — it carries the database password (T-05.1-23).
 */
function parseHostPort(databaseUrl: string | undefined): {host: string; port: string} {
    if (!databaseUrl) return {host: "unknown", port: "unknown"};
    try {
        const url = new URL(databaseUrl);
        return {host: url.hostname || "unknown", port: url.port || "5432"};
    } catch {
        return {host: "unknown", port: "unknown"};
    }
}

/**
 * Resolves server/prisma/prisma.config.ts from this module's own location.
 * This is a config file, not an executable, so it has no platform
 * divergence — but the correct relative distance still differs between dev
 * (this module runs directly from server/src/lib, two directories under
 * server/) and the built image (the compiled module runs from
 * /app/dist/server/lib, while server/prisma/ is copied to a sibling
 * /app/server/prisma, three directories up with a "server/" segment) —
 * mirrors server/test/integration/setup.ts's resolution approach for the
 * config path, extended with a filesystem check for the layout that
 * setup.ts never needs to handle: setup.ts always runs from source, this
 * module runs from both.
 */
function resolvePrismaConfigPath(): string {
    const candidates = [
        path.resolve(__dirname, "../../prisma/prisma.config.ts"),
        path.resolve(__dirname, "../../../server/prisma/prisma.config.ts"),
    ];
    const found = candidates.find((candidate) => existsSync(candidate));
    if (!found) {
        throw new Error(
            `schema-sync: could not resolve server/prisma/prisma.config.ts — tried: ${candidates.join(", ")}`,
        );
    }
    return found;
}

/**
 * Resolves the schema directory (server/prisma/schema) from the already-
 * resolved config path — the config file and the schema directory are
 * always siblings under server/prisma/, in both dev and the built image, so
 * this needs no separate candidate search.
 */
function resolvePrismaSchemaPath(): string {
    return path.join(path.dirname(resolvePrismaConfigPath()), "schema");
}

/**
 * Builds the `prisma migrate deploy` argv as an array — never a shell string
 * (T-05.1-24) — containing only the formal migration-apply subcommand pair
 * and --config. Must never include a data-loss-acceptance flag or a reset
 * flag (T-05.1-20/T-09-10): `migrate deploy` applies only recorded,
 * already-reviewed migrations by design and does not accept either flag in
 * the first place, so there is nothing to omit by discipline here — the
 * absence is structural, not a habit this code has to maintain.
 */
function buildDeployArgv(): string[] {
    return ["migrate", "deploy", `--config=${resolvePrismaConfigPath()}`];
}

/**
 * Builds the `prisma migrate resolve --applied <name>` argv used to
 * baseline a database that already carries the shipped schema (via the old
 * `db push` step) but has no migration history yet. Deliberately always
 * `--applied`, never `--rolled-back` — the latter marks a *failed*
 * migration as rolled back, a different operation this step never performs.
 */
function buildResolveArgv(migrationName: string): string[] {
    return ["migrate", "resolve", "--applied", migrationName, `--config=${resolvePrismaConfigPath()}`];
}

/**
 * Builds the `prisma migrate diff` argv used as the post-baseline drift
 * probe: live datasource (`--from-config-datasource`, reading DATABASE_URL
 * via prisma.config.ts) versus the shipped schema directory
 * (`--to-schema`), with `--exit-code` so divergence is reported as a
 * non-zero exit (0 = no diff, 2 = diff detected, 1 = a genuine CLI error) —
 * this step never writes anything; it only reports.
 */
function buildDriftProbeArgv(): string[] {
    return [
        "migrate",
        "diff",
        "--from-config-datasource",
        "--to-schema",
        resolvePrismaSchemaPath(),
        "--exit-code",
        `--config=${resolvePrismaConfigPath()}`,
    ];
}

const defaultRunCli: RunCliFn = async (argv) => {
    try {
        const {stdout, stderr} = await execFileAsync(process.execPath, [resolvePrismaCliEntrypoint(), ...argv], {
            env: process.env,
            maxBuffer: 10 * 1024 * 1024,
        });
        return {code: 0, stdout, stderr};
    } catch (err) {
        const execErr = err as NodeJS.ErrnoException & {
            code?: number;
            stdout?: string;
            stderr?: string;
        };
        return {
            code: typeof execErr.code === "number" ? execErr.code : 1,
            stdout: execErr.stdout ?? "",
            stderr: execErr.stderr ?? String(execErr.message ?? err),
        };
    }
};

async function connectWithRetry(): Promise<Client | null> {
    const connectionString = process.env.DATABASE_URL;
    for (let attempt = 1; attempt <= REACHABILITY_RETRY_ATTEMPTS; attempt++) {
        const client = new Client({connectionString, connectionTimeoutMillis: REACHABILITY_CONNECT_TIMEOUT_MS});
        try {
            await client.connect();
            return client;
        } catch {
            await client.end().catch(() => {});
            if (attempt < REACHABILITY_RETRY_ATTEMPTS) {
                await sleep(REACHABILITY_RETRY_DELAY_MS);
            }
        }
    }
    return null;
}

const defaultAcquireLock: AcquireLockFn = async () => {
    const {host, port} = parseHostPort(process.env.DATABASE_URL);
    const client = await connectWithRetry();
    if (!client) {
        return {status: "unreachable", host, port};
    }

    try {
        const result = await client.query<{locked: boolean}>(
            "SELECT pg_try_advisory_lock($1) AS locked",
            [ADVISORY_LOCK_KEY],
        );
        const locked = result.rows[0]?.locked === true;
        if (!locked) {
            await client.end().catch(() => {});
            return {status: "not-acquired"};
        }

        return {
            status: "acquired",
            query: async (sql: string) => {
                const result = await client.query(sql);
                return {rows: result.rows as Array<Record<string, unknown>>};
            },
            release: async () => {
                try {
                    await client.query("SELECT pg_advisory_unlock($1)", [ADVISORY_LOCK_KEY]);
                } finally {
                    await client.end().catch(() => {});
                }
            },
        };
    } catch {
        await client.end().catch(() => {});
        return {status: "unreachable", host, port};
    }
};

/**
 * True when no `_prisma_migrations` table exists in the current schema —
 * i.e. this database has never been touched by `prisma migrate`. Runs on
 * the connection already held by `acquireLock()`'s advisory lock, so
 * baseline detection happens inside the same critical section that
 * serializes concurrent starting replicas — no second connection is opened.
 */
async function needsBaseline(query: QueryFn): Promise<boolean> {
    const result = await query(
        `SELECT EXISTS (
           SELECT FROM information_schema.tables
           WHERE table_schema = current_schema()
             AND table_name = '_prisma_migrations'
         ) AS has_history`,
    );
    const row = result.rows[0] as {has_history?: boolean} | undefined;
    return row?.has_history !== true;
}

/**
 * True when at least one application table (created quoted and
 * case-sensitive by Prisma) already exists — distinguishes a database
 * previously synced via `db push` (has data, no migration history: needs
 * baselining) from a genuinely empty one (needs a cold `migrate deploy`,
 * never a baseline).
 */
async function hasApplicationTables(query: QueryFn): Promise<boolean> {
    const result = await query(
        `SELECT EXISTS (
           SELECT FROM information_schema.tables
           WHERE table_schema = current_schema()
             AND table_name IN ('Stack', 'Setting')
         ) AS has_application_tables`,
    );
    const row = result.rows[0] as {has_application_tables?: boolean} | undefined;
    return row?.has_application_tables === true;
}

/**
 * Guarded startup schema-synchronisation step. Applies the project's formal
 * Prisma migrations (`prisma migrate deploy`) before the server starts
 * serving requests, gated by the same four guards this step has always
 * used: an opt-out env var, a bounded reachability retry budget, a
 * non-blocking Postgres advisory lock (so two instances starting against
 * one database never both apply migrations), and an argv that can never
 * accept data loss or trigger a reset. Never throws — every failure mode
 * resolves to a discriminated outcome so the HTTP server can still come up
 * and the operator can read the logs.
 *
 * Automatic baseline branch: a database that already carries application
 * tables from the old schemaless `db push` step, but has no
 * `_prisma_migrations` table yet, is detected via `needsBaseline()` +
 * `hasApplicationTables()` and baselined automatically by recording
 * `BASELINE_MIGRATION_NAME` as applied (`prisma migrate resolve
 * --applied`) before `migrate deploy` runs — zero operator action. A
 * genuinely empty database (no history, no application tables) skips the
 * baseline entirely and gets the schema applied cold. After any baseline, a
 * drift probe (`prisma migrate diff --exit-code`) compares the live schema
 * against the shipped one and logs loudly under the `[schema-sync]` prefix
 * if they still disagree — the residual risk of a partial prior `db push`
 * recording a baseline that doesn't actually match. This step never
 * repairs a detected drift, never forces anything through, and never
 * resets.
 *
 * Opt-out: set DOCKTOR_DB_AUTO_MIGRATE=false to disable this step entirely.
 * DOCKTOR_DB_AUTO_PUSH=false is honoured as a deprecated alias so an
 * operator who deliberately disabled the old `db push` step keeps that
 * opt-out across this upgrade — an explicitly set DOCKTOR_DB_AUTO_MIGRATE
 * always wins over the deprecated alias.
 */
export async function syncDatabaseSchema(deps: SchemaSyncDeps = {}): Promise<SchemaSyncResult> {
    const autoMigrateEnv = process.env.DOCKTOR_DB_AUTO_MIGRATE;
    if (autoMigrateEnv !== undefined) {
        if (autoMigrateEnv === "false") {
            return {outcome: "skipped", detail: "DOCKTOR_DB_AUTO_MIGRATE=false"};
        }
    } else if (process.env.DOCKTOR_DB_AUTO_PUSH === "false") {
        console.warn(
            "[schema-sync] DOCKTOR_DB_AUTO_PUSH is deprecated for disabling this step — set DOCKTOR_DB_AUTO_MIGRATE=false instead. Honouring the deprecated opt-out for now.",
        );
        return {outcome: "skipped", detail: "DOCKTOR_DB_AUTO_PUSH=false (deprecated alias)"};
    }

    const runCli = deps.runCli ?? defaultRunCli;
    const acquireLock = deps.acquireLock ?? defaultAcquireLock;

    try {
        const lockResult = await acquireLock();

        if (lockResult.status === "unreachable") {
            console.error(
                `[schema-sync] database unreachable at ${lockResult.host}:${lockResult.port} after retry budget exhausted — skipping schema sync; the server will still start`,
            );
            return {outcome: "unreachable", detail: `${lockResult.host}:${lockResult.port}`};
        }

        if (lockResult.status === "not-acquired") {
            return {outcome: "lock-not-acquired", detail: "another instance holds the schema-sync advisory lock"};
        }

        try {
            let baselined = false;

            if (await needsBaseline(lockResult.query)) {
                if (await hasApplicationTables(lockResult.query)) {
                    console.info(
                        `[schema-sync] no migration history found but application tables already exist — baselining ${BASELINE_MIGRATION_NAME}`,
                    );
                    const resolveResult = await runCli(buildResolveArgv(BASELINE_MIGRATION_NAME));
                    if (resolveResult.code !== 0) {
                        console.error(
                            `[schema-sync] baseline resolve failed (exit ${resolveResult.code}) — resolve manually:\n${resolveResult.stderr}`,
                        );
                        return {outcome: "failed", detail: resolveResult.stderr || resolveResult.stdout};
                    }
                    console.info(`[schema-sync] baselined ${BASELINE_MIGRATION_NAME}`);
                    baselined = true;
                } else {
                    console.info(
                        "[schema-sync] no migration history and no application tables — treating as a fresh database",
                    );
                }
            }

            const cliResult = await runCli(buildDeployArgv());
            const combinedOutput = `${cliResult.stdout}\n${cliResult.stderr}`.trim();

            if (cliResult.code !== 0) {
                console.error(
                    `[schema-sync] prisma migrate deploy failed (exit ${cliResult.code}) — resolve the schema conflict manually:\n${cliResult.stderr}`,
                );
                return {outcome: "failed", detail: cliResult.stderr || combinedOutput};
            }

            const outcome: SchemaSyncOutcome = NO_PENDING_MIGRATIONS_REGEX.test(combinedOutput)
                ? "already-current"
                : "applied";
            let detail = combinedOutput;

            if (baselined) {
                detail = `baselined ${BASELINE_MIGRATION_NAME}; ${detail}`;

                const driftResult = await runCli(buildDriftProbeArgv());
                if (driftResult.code !== 0) {
                    console.error(
                        `[schema-sync] database was auto-baselined but still diverges from the shipped schema — set DOCKTOR_DB_AUTO_MIGRATE=false to disable this step and resolve manually:\n${driftResult.stdout}\n${driftResult.stderr}`,
                    );
                }
            }

            return {outcome, detail};
        } catch (err) {
            const message = err instanceof Error ? err.message : String(err);
            console.error(`[schema-sync] prisma migrate threw before completing: ${message}`);
            return {outcome: "failed", detail: message};
        } finally {
            await lockResult.release();
        }
    } catch (err) {
        // Defense in depth: syncDatabaseSchema must never throw, regardless
        // of an unexpected failure in a collaborator (T-05.1-22).
        const message = err instanceof Error ? err.message : String(err);
        console.error(`[schema-sync] unexpected error: ${message}`);
        return {outcome: "failed", detail: message};
    }
}
