name: docktor-dev

services:
  db:
    image: postgres:17
    container_name: docktor-db-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docktor
      POSTGRES_PASSWORD: docktor
      POSTGRES_DB: docktor
    volumes:
      - docktor-db-dev:/var/lib/postgresql/data

volumes:
  docktor-db-dev:
