sonar.projectKey=docktor
sonar.projectName=Docktor

sonar.sources=shared/src,server/src,client/src
sonar.tests=server/test,client/test,shared/test
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts

sonar.typescript.lcov.reportPaths=server/.test/coverage/lcov.info,client/.test/coverage/lcov.info,shared/.test/coverage/lcov.info

sonar.coverage.exclusions=**/generated/**,**/node_modules/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts
sonar.exclusions=**/generated/**,**/node_modules/**,**/dist/**
